#!/usr/bin/env python
# coding: utf-8

# In[ ]:


def uti():
    return("YOU MAY BE SUFFERING FROM UTI INFECTION,GET YOUR URINE TEST DONE")
def maleria():
    return("YOU MAY BE SUFFRING FROM MALERIA,GET YOUR MPFM TEST DONE WITH CBC")
def covid():
    return("YOU MAY BE SUFFERING FROM COVID GET YOUR RTPCR TEST,CBC,CRP,D-DIMER TEST DONE")
def typhoid():
    return("YOU MAY BE SUFFERING FROM TYPHOID GET YOUR WIDAL TEST DONE")
def colitis():
    return("YOU MAY BE SUFFERING FROM COLITIS,GET YOUR ABDOMENE ULTRASOUND DONE")
def jaundice():
    return("YOU MAY BE SUFFERING FROM JAUNDICE, GET YOUR SERUM BILLIRUBIN,SGPT,SGOT/LFT TEST DONE ")
def pcod():
    return("YOU MAY BE SUFFERING FROM PCOD,GET YOUR LOWER ABDOMEN ULTRASOUND DONE ")
def piles():
    return("YOU MAY BE SUFFERING FROM PILES GET YOUR COLONOSCOPY DONE")


# In[ ]:





# In[ ]:




